#!/usr/bin/env zsh

local utils_dir=$(cd "$(dirname "$0")" && pwd)
local repo_dir=$(dirname "$utils_dir")
local SSTest_dir="${repo_dir}/.SSTest"
local tag="${1:-1.1.1}"

if [[ ! -d "$SSTest_dir" ]]; then
  git clone https://GitHub.com/YOCKOW/SSTest.git "$SSTest_dir"
fi

cd "$SSTest_dir"
git fetch origin
git checkout "$tag"