#!/usr/bin/env zsh

local utils_dir=$(cd "$(dirname "$0")" && pwd)
local repo_dir=$(dirname "$utils_dir")
local SSTest_dir="${repo_dir}/.SSTest"

echo "Prepare \`SSTest\`."
if ! command -v SSTest 1>/dev/null 2>&1; then
  "${utils_dir}/clone-SSTest"
  cd "$SSTest_dir"
  make build
  PATH="${SSTest_dir}/bin:$PATH"
  export PATH
fi

local -r public_key_id="01F76899E9C1E5B003169A23BEEDB9712A367313"
local has_public_key=true
if ! gpg --list-keys $public_key_id 1>/dev/null 2>&1; then
  echo "Import YOCKOW's Public Key (Temporarily)"
  has_public_key=false
  gpg --fetch-keys "https://GitHub.com/YOCKOW.gpg"
fi

SSTest "${repo_dir}/tests"

if [[ "$has_public_key" != "true" && ! -v GITHUB_ACTIONS ]]; then
  gpg --yes --delete-keys $public_key_id
fi